#!//usr/bin/bash
CENTRAL_SNR=960103340
PERIPHERAL_SNR=683892318
SAMPLE_FOLDER=samples/bluetooth
pushd ${SAMPLE_FOLDER}
west build central_otc -p -b nrf5340dk_nrf5340_cpuapp -d central_otc/build -- -DCONFIG_BT_OTS_CLIENT_LOG_LEVEL_WRN=y -DCONFIG_BT_OTS_LOG_LEVEL_WRN=y -DCONFIG_BT_USER_DATA_LEN_UPDATE=y -DCONFIG_BT_USER_PHY_UPDATE=y -DCONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n -DCONFIG_BT_BUF_ACL_RX_SIZE=502 -DCONFIG_BT_ATT_PREPARE_COUNT=2 -DCONFIG_BT_L2CAP_TX_BUF_COUNT=10 -DCONFIG_BT_L2CAP_TX_MTU=498 -DCONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y -DCONFIG_BT_CONN_TX_MAX=10 -DCONFIG_BT_BUF_ACL_TX_COUNT=10 -DCONFIG_BT_BUF_ACL_TX_SIZE=502 -DCONFIG_BT_CTLR_DATA_LENGTH_MAX=251 -DCONFIG_BT_CTLR_PHY_2M=y -DCONFIG_BT_CTLR_RX_BUFFERS=2 -DCONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=4000000 -Dhci_rpmsg_CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=4000000 -Dhci_rpmsg_CONFIG_BT_CTLR_DATA_LENGTH_MAX=251 -Dhci_rpmsg_CONFIG_BT_BUF_ACL_RX_SIZE=502 -Dhci_rpmsg_CONFIG_BT_BUF_ACL_TX_SIZE=502 -Dhci_rpmsg_CONFIG_BT_MAX_CONN=1
west build peripheral_ots -p -b nrf21540dk_nrf52840 -d peripheral_ots/build  -- -DCONFIG_BT_OTS_LOG_LEVEL_WRN=y -DCONFIG_BT_USER_DATA_LEN_UPDATE=y -DCONFIG_BT_USER_PHY_UPDATE=y -DCONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n -DCONFIG_BT_BUF_ACL_RX_SIZE=502 -DCONFIG_BT_ATT_PREPARE_COUNT=2 -DCONFIG_BT_L2CAP_TX_BUF_COUNT=10 -DCONFIG_BT_L2CAP_TX_MTU=498 -DCONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y -DCONFIG_BT_CONN_TX_MAX=10 -DCONFIG_BT_BUF_ACL_TX_COUNT=10 -DCONFIG_BT_BUF_ACL_TX_SIZE=502 -DCONFIG_BT_CTLR_DATA_LENGTH_MAX=251 -DCONFIG_BT_CTLR_PHY_2M=y -DCONFIG_BT_CTLR_RX_BUFFERS=2 -DCONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=4000000
# west build peripheral_ots -p -b nrf5340dk_nrf5340_cpuapp -d peripheral_ots/build  --pristine -- -DCONFIG_BT_PERIPHERAL_PREF_TIMEOUT=500 -DCONFIG_BT_OTS_LOG_LEVEL_DBG=y
west flash -d central_otc/build --erase -i ${CENTRAL_SNR}
west flash -d peripheral_ots/build -i ${PERIPHERAL_SNR}
popd
